# Generated by Django 5.2.12 on 2026-03-28 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_team_messages', to='teams.team')),
                ('sender_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_team_messages', to='teams.team')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_team_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
