# Generated by Django 5.2.12 on 2026-03-28 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMeeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_team_meetings', to=settings.AUTH_USER_MODEL)),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_team_one', to='teams.team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_team_two', to='teams.team')),
            ],
            options={
                'db_table': 'team_meeting',
                'ordering': ['meeting_date', 'meeting_time'],
            },
        ),
    ]
