# Generated by Django 5.2.12 on 2026-03-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_type', models.TextField(blank=True, null=True)),
                ('channel_value', models.TextField(blank=True, null=True)),
                ('is_primary', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'contact_channel',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='MeetingSchedule',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('frequency', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting_schedule',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mission_statement', models.TextField(blank=True, null=True)),
                ('created_date', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=0)),
                ('slack_channels', models.TextField(blank=True, null=True)),
                ('daily_startup_time', models.TextField(blank=True, null=True)),
                ('team_wiki', models.TextField(blank=True, null=True)),
                ('development_focus_areas', models.TextField(blank=True, null=True)),
                ('key_skills_technologies', models.TextField(blank=True, null=True)),
                ('dependency_id', models.IntegerField()),
                ('dependency_type', models.TextField(blank=True, null=True)),
                ('dependency_description', models.TextField(blank=True, null=True)),
                ('channel', models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.contactchannel')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.department')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.meetingschedule')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='CodeRepository',
            fields=[
                ('repo_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('created_date', models.TextField(blank=True, null=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='teams.team')),
            ],
            options={
                'db_table': 'codeRepository',
            },
        ),
    ]
