# Generated by Django 5.2.12 on 2026-03-25 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_head', models.ForeignKey(blank=True, db_column='department_head', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='teams.employee')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.TextField(blank=True, null=True)),
                ('slack_channels', models.TextField(blank=True, null=True)),
                ('daily_standup_time', models.TextField(blank=True, null=True)),
                ('team_wiki', models.TextField(blank=True, null=True)),
                ('development_focus_areas', models.TextField(blank=True, null=True)),
                ('key_skills_technologies', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.department')),
                ('team_leader', models.ForeignKey(blank=True, db_column='team_leader', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='teams.employee')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('codebase', models.TextField(blank=True, null=True)),
                ('jira_link', models.TextField(blank=True, null=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.team')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='teams.team'),
        ),
    ]
