# Generated by Django 5.2.12 on 2026-03-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
